### ISSUE TITLE
[MISCELLANEOUS] It is possible to have a release version 

### ISSUE THREAD

**Issue by skychiarottoa** [bstillitano/Scyther#14]
We are trying to integrate you library with spm.
It is possible to have fixed release version?

Thanks

**Comment by bstillitano** [comment]
Hi

Thanks for reaching out. I will tag a release in the next couple of hours or so. Will update you here once it's done 😄

**Comment by bstillitano** [comment]
@skychiarottoa this is now done. You should be able to point SPM to version `1.0.0`. Please let me know any issues.
